export const ADD_URL = 'ADD_URL';
export const ADD_URL_FAILED = 'ADD_URL_FAILED';
export const REMOVE_URL = 'REMOVE_URL';
export const GET_INITIAL_STATE = 'GET_INITIAL_STATE';
export const HIDRATE_INITIAL_STATE = 'HIDRATE_INITIAL_STATE';
